### ISSUE TITLE
OSError: No file or directory found at /Users/tulpar/Project/liveness_system/Server/Models/Liveness_model1.h5

### ISSUE THREAD

**Issue by MyraBaba** [Ahmed-Rushdi/liveness_system#1]
Hi,

error: 

`
model1 = keras.models.load_model(os.path.join(package_directory, 'Models/Liveness_model1.h5'))
model2 = keras.models.load_model(os.path.join(package_directory, 'Models/Liveness_model2.h5'))`

OSError: No file or directory found at /Users/tulpar/Project/liveness_system/Server/Models/Liveness_model1.h5

**Comment by Ahmed-Rushdi** [comment]
The models are too big to be hosted on github. 
Here is the link to the Models Folder hosted on google drive:
https://drive.google.com/drive/folders/1DMfr07Z017H3F0hwy_vZpZo-QGQwd7is?usp=sharing
